// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Model.Configuration;

#nullable disable

namespace StarWars.Model.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    [Migration("20241009095351_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("StarWars.Model.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FACTION");

                    b.Property<string>("Homeworld")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HOMEWORLD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SPECIES");

                    b.HasKey("Id");

                    b.ToTable("CHARACTERS");
                });
#pragma warning restore 612, 618
        }
    }
}
